language: php

sudo: false

cache:
    directories:
        - $HOME/im

php:
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4
    - 5.3

env:
    - IMAGEMAGICK_VERSION=git7
    - IMAGEMAGICK_VERSION=git6
    - IMAGEMAGICK_VERSION=7.0.1-0
    - IMAGEMAGICK_VERSION=6.9.2-0
    - IMAGEMAGICK_VERSION=6.8.7-0
    - IMAGEMAGICK_VERSION=6.7.5-3
    - IMAGEMAGICK_VERSION=6.6.0-9
    - IMAGEMAGICK_VERSION=6.5.3-10
    
    # Include individual commits like this:
    # - IMAGEMAGICK_VERSION=commit_25553302a6d5f736b55e60109600dfbce5fbea48

matrix:
  exclude:
    - php: 5.3
      env: IMAGEMAGICK_VERSION=6.8.7-0
    - php: 5.3
      env: IMAGEMAGICK_VERSION=6.7.5-3
    - php: 5.3
      env: IMAGEMAGICK_VERSION=6.6.0-9
    - php: 5.3
      env: IMAGEMAGICK_VERSION=6.4.0-11
    - php: 5.4
      env: IMAGEMAGICK_VERSION=6.8.7-0
    - php: 5.4
      env: IMAGEMAGICK_VERSION=6.7.5-3
    - php: 5.4
      env: IMAGEMAGICK_VERSION=6.6.0-9
    - php: 5.4
      env: IMAGEMAGICK_VERSION=6.4.0-11
    - php: 5.5
      env: IMAGEMAGICK_VERSION=6.7.5-3
    - php: 5.5
      env: IMAGEMAGICK_VERSION=6.6.0-9
    - php: 5.5
      env: IMAGEMAGICK_VERSION=6.4.0-11

before_script:
    - for file in tests/*.phpt; do grep $(basename $file) package.xml >/dev/null || (echo "Missing $file from package.xml" ; exit 1); done
    - bash ./imagemagick_dependency.sh "${IMAGEMAGICK_VERSION}"

script:
    - export NO_INTERACTION=1
    - export REPORT_EXIT_STATUS=1
    - export SKIP_SLOW_TESTS=1
    - export TEST_PHP_EXECUTABLE=`which php`
    - export PHP_IMAGICK_VERSION=$(php -r '$sxe = simplexml_load_file ("package.xml"); echo (string) $sxe->version->release;')
    - . ./configure-cflags.sh
    - phpize
    - ./configure --with-imagick="${HOME}/im/imagemagick-${IMAGEMAGICK_VERSION}"
    - make
    - php run-tests.php -d extension=imagick.so -d extension_dir=modules -n ./*.phpt
    - php run-tests.php -d extension=imagick.so -d extension_dir=modules -n ./tests/*.phpt
    - for i in `ls tests/*.out 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done

matrix:
  allow_failures:
    - env: IMAGEMAGICK_VERSION=git6
    - env: IMAGEMAGICK_VERSION=git7
